---
apiVersion: v1
kind: Secret
metadata:
  name: image-tool-s3
  namespace: image-tool
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: XXXXXXXXXXXXXXXXXXXX
  AWS_SECRET_ACCESS_KEY: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
